import assert from 'node:assert/strict'
import { describe, it } from 'node:test'

import { createNewCard } from '../../fsrs/scheduler'

import { createConceptProgress } from '../rotta'
import {
  createSession,
  endSession,
  recordAnswer,
  selectNextItem,
  type DueCard,
} from '../session'
import type { ConceptProgress, QuizItem } from '../types'

function item(overrides: Partial<QuizItem> = {}): QuizItem {
  return {
    id: 'i',
    concetto_id: 'c1',
    argomento_numero: 1,
    fase_rotta: 'riconosci',
    testo_domanda: '?',
    risposta_corretta: true,
    spiegazione: 'x',
    ...overrides,
  }
}

describe('createSession', () => {
  it('returns a blank session', () => {
    const s = createSession('user1', {
      durata_target_minuti: 20,
      modalita: 'studio',
    })
    assert.equal(s.user_id, 'user1')
    assert.equal(s.items_total, 0)
    assert.equal(s.items_presented.length, 0)
    assert.equal(s.argomenti_used.size, 0)
  })
})

describe('selectNextItem (studio)', () => {
  it('returns null when there are no candidates', () => {
    const s = createSession('u', { durata_target_minuti: 10, modalita: 'studio' })
    assert.equal(selectNextItem(s, [], new Map(), []), null)
  })

  it('prefers due cards over new items', () => {
    const s = createSession('u', { durata_target_minuti: 10, modalita: 'studio' })
    const itemA = item({ id: 'A', concetto_id: 'c1', argomento_numero: 1 })
    const itemB = item({ id: 'B', concetto_id: 'c2', argomento_numero: 2 })
    const progresses = new Map<string, ConceptProgress>([
      ['c1', createConceptProgress('c1')],
      ['c2', createConceptProgress('c2')],
    ])
    const due: DueCard[] = [{ quiz_item_id: 'B', card: createNewCard() }]
    const result = selectNextItem(s, due, progresses, [itemA, itemB])
    assert.equal(result?.id, 'B')
  })

  it('interleaves across argomenti (avoids repeating last shown)', () => {
    const s = createSession('u', { durata_target_minuti: 10, modalita: 'studio' })
    const i1 = item({ id: '1', concetto_id: 'c1', argomento_numero: 1 })
    const i2 = item({ id: '2', concetto_id: 'c2', argomento_numero: 2 })
    const progresses = new Map<string, ConceptProgress>([
      ['c1', createConceptProgress('c1')],
      ['c2', createConceptProgress('c2')],
    ])
    const s2 = {
      ...s,
      items_presented: ['1'],
      argomenti_used: new Set([1]),
    }
    const result = selectNextItem(s2, [], progresses, [i1, i2])
    assert.equal(result?.argomento_numero, 2)
  })

  it('excludes already-presented items', () => {
    const s = createSession('u', { durata_target_minuti: 10, modalita: 'studio' })
    const i1 = item({ id: '1', concetto_id: 'c1', argomento_numero: 1 })
    const progresses = new Map([['c1', createConceptProgress('c1')]])
    const s2 = { ...s, items_presented: ['1'] }
    assert.equal(selectNextItem(s2, [], progresses, [i1]), null)
  })

  it('skips concepts already in automatizza', () => {
    const s = createSession('u', { durata_target_minuti: 10, modalita: 'studio' })
    const i1 = item({ id: '1', concetto_id: 'c1', fase_rotta: 'automatizza' })
    const progresses = new Map<string, ConceptProgress>([
      ['c1', { ...createConceptProgress('c1'), current_phase: 'automatizza' }],
    ])
    assert.equal(selectNextItem(s, [], progresses, [i1]), null)
  })
})

describe('selectNextItem (simulazione)', () => {
  it('returns items in allItems order (pre-generated by simulator)', () => {
    const s = createSession('u', {
      durata_target_minuti: 20,
      modalita: 'simulazione',
    })
    const items = [item({ id: '1' }), item({ id: '2' })]
    assert.equal(selectNextItem(s, [], new Map(), items)?.id, '1')
  })
})

describe('recordAnswer', () => {
  it('updates session counts and progress on a correct answer', () => {
    const s = createSession('u', { durata_target_minuti: 10, modalita: 'studio' })
    const card = createNewCard()
    const progress = createConceptProgress('c1')
    const it = item({ id: 'i', risposta_corretta: true })

    const out = recordAnswer({
      session: s,
      item: it,
      currentCard: card,
      progress,
      answer: true,
      tempoMs: 3000,
    })

    assert.equal(out.result.corretta, true)
    assert.equal(out.session.items_total, 1)
    assert.equal(out.session.items_correct, 1)
    assert.equal(out.progress.phase_items_completed, 1)
    assert.ok(out.session.argomenti_used.has(1))
  })

  it('records a wrong answer under the corresponding argomento', () => {
    const s = createSession('u', { durata_target_minuti: 10, modalita: 'studio' })
    const it = item({ id: 'i', argomento_numero: 7, risposta_corretta: true })

    const out = recordAnswer({
      session: s,
      item: it,
      currentCard: createNewCard(),
      progress: createConceptProgress('c1'),
      answer: false,
      tempoMs: 4000,
    })

    assert.equal(out.result.corretta, false)
    assert.equal(out.session.errori_per_argomento.get(7), 1)
  })

  it('NO penalty in Origina: wrong answer does not produce a lapse', () => {
    const s = createSession('u', { durata_target_minuti: 10, modalita: 'studio' })
    const progress: ConceptProgress = {
      ...createConceptProgress('c1'),
      current_phase: 'origina',
    }
    const it = item({ fase_rotta: 'origina', risposta_corretta: true })

    const out = recordAnswer({
      session: s,
      item: it,
      currentCard: createNewCard(),
      progress,
      answer: false,
      tempoMs: 5000,
    })

    assert.equal(out.result.corretta, false)
    assert.equal(out.card.lapses, 0)
    assert.notEqual(out.card.state, 'new')
  })
})

describe('endSession', () => {
  it('computes durata, percentuale, breakdown errori', () => {
    const started = new Date('2026-01-01T10:00:00Z')
    const now = new Date('2026-01-01T10:10:00Z')
    const baseSession = createSession(
      'u',
      { durata_target_minuti: 10, modalita: 'studio' },
      started,
    )
    const s = {
      ...baseSession,
      items_total: 10,
      items_correct: 7,
      argomenti_used: new Set([1, 2, 3]),
      errori_per_argomento: new Map([
        [1, 2],
        [3, 1],
      ]),
      concetti_avanzati: ['c1'],
    }

    const summary = endSession(s, now)
    assert.equal(summary.items_total, 10)
    assert.equal(summary.items_correct, 7)
    assert.equal(summary.percentuale, 70)
    assert.equal(summary.durata_secondi, 600)
    assert.deepEqual(summary.argomenti_mescolati, [1, 2, 3])
    assert.deepEqual(summary.errori_per_argomento, { 1: 2, 3: 1 })
    assert.deepEqual(summary.fasi_avanzate, ['c1'])
  })
})
